### ISSUE TITLE
Persisting saga state

### ISSUE THREAD

**Issue by theoden-dd** [meadsteve/talepy#17]
What about instance crash in a middle step? Especially if it was a N of M retry. Who should persist the transaction metadata and how a recovery is supposed to happen?

**Comment by meadsteve** [comment]
@theoden-dd with the way I've currently designed this each step is responsible for its own clean up. I've often implemented this with a catch that tidies up and then rethrows to fail the transaction. If you find a step has a lot of intermediate states that need cleaning it might be a sign to split it into a few different steps
